#服务名称
server:
  servlet:
    context-path: /smartParking

spring:
  profiles:
      active: local

  #数据源配置
  datasource:
    #开启Druid监控功能
    druid:
      # 初始化连接池时创建的连接数
      initial-size: 10
      # 连接池中最小空闲连接数
      min-idle: 10
      # 连接池中最大活跃连接数
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 10000
      # 配置间隔多久才进行一次检测, 检测需要关闭的空闲连接, 单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间, 单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 用于连接池检测连接是否有效的SQL语句
      validation-query: SELECT 'x'
      # 是否保持长连接
      keep-alive: true

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:com/sp/cjgc/**/mapper/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
    # 是否开启驼峰命名
    map-underscore-to-camel-case: true

# 全局参数
global:
  # 是否开启token校验 true|开启  false｜关闭
  token: true
  # 定义token的key名
  authorization: Authorization
  # 是否开启控制闸 true|开启  false｜关闭
  controlGate: false
